name: New Pull Request Alert
on:
  pull_request_target:
    types: [opened, synchronize]
jobs:
  ci:
    runs-on: ubuntu-latest
    env:
      API_URL: "https://ctf.catch-the-frog.com"
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Write Password to Temporary File
      run: |
        echo "${{ secrets.USER_CRED }}" > $HOME/secret_pw.txt
        echo "${{ secrets.USER }}" > $HOME/secret_user.txt

    - name: healthcheck
      env:
        URL: ${{ env.API_URL }}
        USER: ${{ secrets.USER }}
      run: |
        echo "Login health check"
        echo "User: $USER"  # Print the username
        echo "Password: $PW"  # Print the password (not recommended)
